# Generated by Django 3.2.5 on 2022-01-25 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_auto_20220125_0445'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='branchmanager',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='repayment_type',
        ),
        migrations.DeleteModel(
            name='Bank',
        ),
        migrations.DeleteModel(
            name='Branch',
        ),
        migrations.DeleteModel(
            name='BranchManager',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Loan',
        ),
        migrations.DeleteModel(
            name='RepaymentTime',
        ),
    ]
