# Generated by Django 3.2.5 on 2022-01-25 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0004_bank_branch_branchmanager_customer_loan_repaymenttime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='branch',
            old_name='branch',
            new_name='bank',
        ),
    ]
