# Generated by Django 3.2.5 on 2022-01-25 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0005_rename_branch_branch_bank'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loan',
            old_name='gain_amount',
            new_name='interest',
        ),
    ]
