# Generated by Django 3.2.5 on 2022-01-25 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0006_rename_gain_amount_loan_interest'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='deposit',
            field=models.FloatField(default=50000),
            preserve_default=False,
        ),
    ]
