# Generated by Django 3.2.5 on 2022-01-25 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0007_customer_deposit'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerLoad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.customer')),
                ('load', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.loan')),
            ],
        ),
    ]
