# Generated by Django 3.2.5 on 2022-01-25 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0008_customerload'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomerLoad',
            new_name='CustomerLoan',
        ),
        migrations.RenameField(
            model_name='customerloan',
            old_name='load',
            new_name='loan',
        ),
    ]
