# Generated by Django 3.2.5 on 2022-01-26 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0009_auto_20220125_0839'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(max_length=250)),
                ('first_customer', models.IntegerField()),
                ('second_customer', models.IntegerField(blank=True, null=True)),
                ('transaction_amount', models.IntegerField()),
                ('log_datetime', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField()),
            ],
        ),
    ]
