# Generated by Django 3.2.5 on 2022-01-26 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0011_branchmanager_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branchmanager',
            name='username',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
